components:
  schemas:
    GetMapCenterRs:
      type: object
      properties:
        search_map_center:
          type: object
          description: Search center coordinates stored in the user record.
          properties:
            longitude:
              type: number
              example: -74.0060
            latitude:
              type: number
              example: 40.7128
        sell_map_center:
          type: object
          description: Sell center coordinates stored in the seller record.
          properties:
            longitude:
              type: number
              example: -118.2437
            latitude:
              type: number
              example: 34.0522

    SaveMapCenterRq:
      type: object
      properties:
        longitude:
          type: number
          example: -74.0060
        latitude:
          type: number
          example: 40.7128
        type:
          type: string
          enum: 
            - search
            - sell
          example: search
        description: |
          The request object to save a map center. `type` should be either 
          `search` for user settings or `sell` for seller settings.

    SaveMapCenterRs:
      type: object
      properties:
        search_map_center:
          type: object
          description: Search center coordinates stored in the user record.
          properties:
            longitude:
              type: number
              example: -74.0060
            latitude:
              type: number
              example: 40.7128
        sell_map_center:
          type: object
          description: Sell center coordinates stored in the seller record.
          properties:
            longitude:
              type: number
              example: -118.2437
            latitude:
              type: number
              example: 34.0522