components:
  schemas:
    Membership:
      type: object
      properties:
        user_id:
          type: string
          description: Unique identifier for the user
          example: 66741c62b175e7d059a2639e
        membership_class:
          $ref: './enum/MembershipType.yml#/components/schemas/MembershipType'
        mappi_balance:
          type: number
          description: The balance of mappi units for the user
          example: 100
        membership_expiration:
          type: string
          format: date-time
          description: The expiration date of the current membership
          example: 2025-02-12T19:24:20.206+00:00
        _id:
          type: string
          description: Unique identifier for the membership record
          example: 6673a08503852cb0c9b618d9
        __v:
          type: number
          description: Version key for the membership document
          example: 0
      required:
        - user_id
        - membership_class
        - mappi_balance
        - membership_expiration

    UpgradeMembershipRq:
      type: object
      properties:
        user_id:
          type: string
          description: Unique identifier for the user
          example: 66741c62b175e7d059a2639e
        tier_class:
          type: string
          description: The target membership tier (e.g., Gold, Double Gold)
          example: Gold
        durationWeeks:
          type: number
          description: Duration of the new membership in weeks
          example: 4
        mappiAllowance:
          type: number
          description: Additional mappi units provided with the new tier
          example: 100
      required:
        - user_id
        - tier_class
        - durationWeeks
        - mappiAllowance

    UpgradeMembershipRs:
      type: object
      properties:
        membership_class:
          type: string
          description: The updated membership class
          example: Gold
        mappi_balance:
          type: number
          description: Updated mappi balance after the upgrade
          example: 200
        membership_expiration:
          type: string
          format: date-time
          description: Updated expiration date of the membership
          example: 2025-02-12T19:24:20.206+00:00
      required:
        - membership_class
        - mappi_balance
        - membership_expiration
