components:
  schemas:
    GetAllSellersRq:
      type: object
      properties:
        origin:
          type: object
          properties:
            lat:
              type: number
              example: 40.7128
            lng:
              type: number
              example: -74.0060
        radius:
          type: number
          example: 15

    GetAllSellersRs:
      type: array
      items:
        type: object
        properties:
          seller_id:
            type: string
            example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
          name:
            type: string
            example: Test Seller
          description:
            type: string
            example: This is a sample seller description.
          seller_type:
            type: string
            example: Pioneer
          image:
            type: string
            example: http://example.com/image.jpg
          address:
            type: string
            example: 1234 Test St, Test City, SC 12345
          sale_items:
            type: string
            example: Test Item 1, Test Item 2
          average_rating:
            type: object
            properties:
              $numberDecimal:
                type: string
                example: 4.5
            required:
              - $numberDecimal
          trust_meter_rating:
            $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
          sell_map_center:
            type: object
            properties:
              type:
                type: string
                example: Point
              coordinates:
                type: array
                items:
                  type: number
                example: [-73.856077, 40.848447]
            required:
              - type
              - coordinates
          order_online_enabled_pref:
            type: boolean
            example: true
          _id:
            type: string
            example: 666c84b9d77068c6efeeaa1a
          __v:
            type: number
            example: 0
        required:
          - seller_id
          - name
          - description
          - seller_type
          - average_rating
          - trust_meter_rating
          - sell_map_center
          - order_online_enabled_pref
          - _id
          - __v

    GetSingleSellerRs:
      type: object
      properties:
        seller_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        name:
          type: string
          example: Test Seller
        description:
          type: string
          example: This is a sample seller description.
        seller_type:
          type: string
          example: Pioneer
        image:
          type: string
          example: http://example.com/image.jpg
        address:
          type: string
          example: 1234 Test St, Test City, SC 12345
        sale_items:
          type: string
          example: Test Item 1, Test Item 2
        average_rating:
          type: object
          properties:
            $numberDecimal:
              type: string
              example: 4.5
          required:
            - $numberDecimal
        trust_meter_rating:
          $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
        sell_map_center:
          type: object
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              items:
                type: number
              example: [-73.856077, 40.848447]
          required:
            - type
            - coordinates
        order_online_enabled_pref:
          type: boolean
          example: true
        _id:
          type: string
          example: 666c84b9d77068c6efeeaa1a
        __v:
          type: number
          example: 0
      required:
        - seller_id
        - name
        - description
        - seller_type
        - average_rating
        - trust_meter_rating
        - sell_map_center
        - order_online_enabled_pref
        - _id
        - __v

    GetSellerRegistrationRq:
      type: object
      properties:
        currentUser:
          type: object
          properties:
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0    
      required:
        - currentUser

    GetSellerRegistrationRs:
      type: object
      properties:
        currentSeller:
          type: object
          properties:
            seller_id:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            name:
              type: string
              example: Test Seller
            description:
              type: string
              example: This is a sample seller description.
            seller_type:
              type: string
              example: Pioneer
            image:
              type: string
              example: http://example.com/image.jpg
            address:
              type: string
              example: 1234 Test St, Test City, SC 12345
            sale_items:
              type: string
              example: Test Item 1, Test Item 2
            average_rating:
              type: object
              properties:
                $numberDecimal:
                  type: string
                  example: 4.5
              required:
                - $numberDecimal
            trust_meter_rating:
              $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
            sell_map_center:
              type: object
              properties:
                type:
                  type: string
                  example: Point
                coordinates:
                  type: array
                  items:
                    type: number
                  example: [-73.856077, 40.848447]
              required:
                - type
                - coordinates
            order_online_enabled_pref:
              type: boolean
              example: true
            _id:
              type: string
              example: 666c8c2eac7df1b07197b5dd
            __v:
              type: number
              example: 0
          required:
            - seller_id
            - name
            - description
            - seller_type
            - average_rating
            - trust_meter_rating
            - sell_map_center
            - order_online_enabled_pref
            - _id
            - __v
      
    RegisterSellerRq:
      type: object
      properties:
        json:
          type: object
          properties:
            seller_id:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            name:
              type: string
              example: Test Seller
            description:
              type: string
              example: This is a sample seller description.
            seller_type:
              type: string
              example: Pioneer
            image:
              type: string
              example: http://example.com/image.jpg
            address:
              type: string
              example: 1234 Test St, Test City, SC 12345
            sale_items:
              type: string
              example: Test Item 1, Test Item 2
            average_rating:
              type: object
              properties:
                $numberDecimal:
                  type: string
                  example: 4.5
              required:
                - $numberDecimal
            trust_meter_rating:
              $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
            sell_map_center:
              type: object
              properties:
                type:
                  type: string
                  example: Point
                coordinates:
                  type: array
                  items:
                    type: number
                  example: [-73.856077, 40.848447]
              required:
                - type
                - coordinates
            order_online_enabled_pref:
              type: boolean
              example: true
          required:
            - seller_id
            - name
            - description
            - seller_type
            - average_rating
            - trust_meter_rating
            - sell_map_center
            - order_online_enabled_pref
            - _id
            - __v
      required:
        - json

    RegisterSellerRs:
      type: object
      properties:
        seller:
          type: object
          properties:
            seller_id:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            name:
              type: string
              example: Test Seller
            description:
              type: string
              example: This is a sample seller description.
            image:
              type: string
              example: http://example.com/image.jpg
            address:
              type: string
              example: 1234 Test St, Test City, SC 12345
            sale_items:
              type: string
              example: Test Item 1, Test Item 2
            sell_map_center:
              type: object
              properties:
                type:
                  type: string
                  example: Point
                coordinates:
                  type: array
                  items:
                    type: number
                  example: [-73.856077, 40.848447]
              required:
                - type
                - coordinates
            order_online_enabled_pref:
              type: boolean
              example: true

      DeleteSellerRs:
        type: object
        properties:
          message:
            type: string
            example: Seller deleted successfully.
          deletedSeller:
            type: object
            properties:
              seller_id:
                type: string
                example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
              name:
                type: string
                example: Test Seller
              description:
                type: string
                example: This is a sample seller description.
              image:
                type: string
                example: http://example.com/image.jpg
              address:
                type: string
                example: 1234 Test St, Test City, SC 12345
              sale_items:
                type: string
                example: Test Item 1, Test Item 2
              average_rating:
                type: object
                properties:
                  $numberDecimal:
                    type: string
                    example: 4.5
                required:
                  - $numberDecimal
              trust_meter_rating:
                $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
              sell_map_center:
                type: object
                properties:
                  type:
                    type: string
                    example: Point
                  coordinates:
                    type: array
                    items:
                      type: number
                    example: [-73.856077, 40.848447]
                required:
                  - type
                  - coordinates
              order_online_enabled_pref:
                type: boolean
                example: true
              _id:
                type: string
                example: 666c84b9d77068c6efeeaa1a
              __v:
                type: number
                example: 0
            required:
              - seller_id
              - name
              - description
              - average_rating
              - trust_meter_rating
              - sell_map_center
              - order_online_enabled_pref
              - _id
              - __v
