components:
  schemas:
    GetUserPreferencesRs:
      type: object
      properties:
        user_settings_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        user_name:
          type: string
          example: Test User
        email:
          type: string
          example: test_user_preferences@example.com
        phone_number:
          type: number
          example: 123456789
        image:
          type: string
          example: https://example.com/image.jpg
        findme_preference:
          type: string
          example: deviceGPS
        trust_meter_rating:
          $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
        search_map_center:
          type: object
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              items:
                type: number
              example: [-73.856077, 40.848447]
          required:
            - type
            - coordinates
        _id:
          type: string
          example: 6673a08503852cb0c9b618d9
        __v:
          type: number
          example: 0
      required:
        - user_settings_id

    AddUserPreferencesRq:
      type: object
      properties:
        user_settings_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        user_name:
          type: string
          example: Test User
        email:
          type: string
          example: test_user_preferences@example.com
        phone_number:
          type: number
          example: 1234567890
        image:
          type: string
          example: https://example.com/image.jpg
        findme_preference:
          type: string
          example: deviceGPS
        trust_meter_rating:
          $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
        search_map_center:
          type: object
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              items:
                type: number
              example: [-73.856077, 40.848447]
          required:
            - type
            - coordinates
      required:
        - user_settings_id

    AddUserPreferencesRs:
      type: object
      properties:
        user_settings_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        user_name:
          type: string
          example: Test User
        email:
          type: string
          example: test_user_preferences@example.com
        phone_number:
          type: number
          example: 1234567890
        image:
          type: string
          example: https://example.com/image.jpg
        findme_preference:
          type: string
          example: deviceGPS
        trust_meter_rating:
          $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
        search_map_center:
          type: object
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              items:
                type: number
              example: [-73.856077, 40.848447]
          required:
            - type
            - coordinates
        _id:
          type: string
          example: 66741c62b175e7d059a2639e
        __v:
          type: number
          example: 0
      required:
        - user_settings_id

    UpdateUserPreferencesRq:
      type: object
      properties:
        user_settings_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        user_name:
          type: string
          example: Test User
        email:
          type: string
          example: test_user_preferences@example.com
        phone_number:
          type: number
          example: 1234567890
        image:
          type: string
          example: https://example.com/image.jpg
        findme_preference:
          type: string
          example: deviceGPS
        trust_meter_rating:
          $ref: '/api/docs/enum/TrustMeterScale.yml#/components/schemas/TrustMeterScale'
        search_map_center:
          type: object
          properties:
            type:
              type: string
              example: Point
            coordinates:
              type: array
              items:
                type: number
              example: [-73.856077, 40.848447]
          required:
            - type
            - coordinates
      required:
        - user_settings_id
