components:
  schemas:
    AuthenticateUserRq:
      type: object
      properties:   
        user:
          type: object
          properties:
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
          required:
            - pi_uid
            - pi_username
            - user_name
      required:
        - user

    AuthenticateUserRs:
      type: object
      properties:
        user:
          type: object
          properties:
            _id:
              type: string
              example: 666bbae4a05bcc3d8dfab563
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
            __v:
              type: integer
              example: 0
          required:
            - _id
            - pi_uid
            - pi_username
            - user_name
            - __v
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZiYmFlNGEwNWJjYzNkOGRmYWI1NjMiLCJpYXQiOjE3MTgzMzk0MDksImV4cCI6MTcyMDkzMTQwOX0.gFz-EdHoOqz3-AuFX5R4uGtruFaTMH8sTOXEX-3c7yw
      required:
        - user
        - token

    GetUserRs:
      type: object
      properties:
        user:
          type: object
          properties:
            _id:
              type: string
              example: 666bbae4a05bcc3d8dfab563
            pi_uid:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            pi_username:
              type: string
              example: test_alias
            user_name:
              type: string
              example: Test Alias
            __v:
              type: integer
              example: 0
          required:
            - _id
            - pi_uid
            - pi_username
            - user_name
            - __v       
      required:
        - user
