components:
  schemas:
    TrustMeterScale:
      type: number
      enum:
        - 0
        - 50
        - 80
        - 100
      description: The trust meter scale measured in increments for the seller.
