name: Map of Pi Build

# Controls when the workflow will execute
on:
  # Triggers the workflow on push or pull request events for the "main" and "dev" branch
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    # The sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

        # Backend CI/CD Process
      - name: Install Dependencies for Backend
        run: npm install

      - name: Execute Tests for Backend
        run: npm run test -- --passWithNoTests
